#ifndef _EXTI_CONFIG_H_
#define _EXTI_CONFIG_H_


/* choose SENSING MODE IF :
 * RISING_EDGE , FALLING_EDGE , LOW_LENEL , ANY_LOGIC
 */
#define EXTI0_SENSING_MODE		RISING_EDGE
#define EXTI1_SENSING_MODE		RISING_EDGE

/* choose SENSING MODE IF :
 * RISING_EDGE , FALLING_EDGE
 */
#define EXTI2_SENSING_MODE		RISING_EDGE




#endif
